### ISSUE TITLE
Backslash

### ISSUE THREAD

**Issue by chachak** [dfs-minded/indexer-plus-plus#26]
This command:

ifind / -iname "*.mp3" -fprintf C:\Results.txt %h%\%p

is giving me an extra '%' character in every occurrence. What I´m doing wrong?

TY

**Comment by chachak** [comment]
I mean:

[url=https://postimages.org/][img]https://s2.postimg.org/iidra4h49/Backslash.png[/img][/url]

The slash also disappears when publishing my comment here.

**Comment by dfs-minded** [comment]
Hi, @chachak! Thank you for reporting this nice issue.

As far as I understood, you want to print full file path to all .mp3 files on your machine.
There was a bug, so you have to download a new installer from the website.

Than use the following query: **ifind / -iname "*.mp3" -fprintf C:\Results.txt %h\\\\%p**
(backslash should be escaped with another backslash)

Please let me know if it has worked for you or if any other issues arise or if I can help you more.

Kind regards,
Anna
