### ISSUE TITLE
Open by default in the taskbar notification area

### ISSUE THREAD

**Issue by op3nus3r** [dfs-minded/indexer-plus-plus#27]
When starting windows the window opens on the desktop, it would be better if it opened by default in the taskbar notification area.

Thanks for this application, I hope to be able to replace soon "everything" by voidtools which is super efficient but not opensource unfortunately.

**Comment by dfs-minded** [comment]
Hi, @op3nus3r! Thank you for the suggestion and for warm words! I do appreciate it and trying to improve Indexer++ further. I will include this improvement in the next release.

**Comment by op3nus3r** [comment]
That's great, thank you very much for your work. :)

**Comment by dfs-minded** [comment]
Hi @op3nus3r! In the latest release (v0.5) which is now already available, your feature must work.
If there any issues or other feature/bug requests, I will be happy to implement/fix them.
Regards, Anna

**Comment by op3nus3r** [comment]
Thank you very much for your work @dfs-minded, I will test with pleasure :)
