### ISSUE TITLE
Indexer++ Beta v0.4 does not open on windows

### ISSUE THREAD

**Issue by pitastrudl** [dfs-minded/indexer-plus-plus#31]
I installed it, opened it, and it only opens in the notification area, but when I double click it, the icon just dissapears. Running windows 10 pro x64.

**Comment by dfs-minded** [comment]
Hi @pitastrudl!
Thank you for reporting this issue. Before we dive deeper, have you tried simple things like restarting your PC and reinstalling Indexer++? I've tested Indexer++ on Windows 10 x64 on the different machines, so it should work). Please let me know if it still not launching.
