### ISSUE TITLE
Embed icon into the executable

### ISSUE THREAD

**Issue by smaragdus** [dfs-minded/indexer-plus-plus#34]
It seems that  the icon is not embedded into the executable (**Indexer++ Beta.exe**), screen:

![indexer 0 5 beta - 2018-03-28 - 002](https://user-images.githubusercontent.com/9025757/38050228-f9dccb14-32d2-11e8-8d97-bccb31060de3.png)

When "Desktop Shortcut" option is not chosen on program installation the user needs to manually change the program icon.

**Comment by idietmoran** [comment]
This is a fairly straight forward fix, you can either just edit the `.xaml` files to include the `icon` tag, or set the icons in visual studio. I can make a PR.

**Comment by idietmoran** [comment]
I got it working here, not really sure how to upload the changes other than the VS project files, as it did not modify any files.

This is all I did.

![devenv_2018-03-30_18-50-37](https://user-images.githubusercontent.com/15315637/38156398-9a7c323e-344b-11e8-8951-8a290ca4c183.png)

**Comment by dfs-minded** [comment]
Hi guys! Thank you @smaragdus for reporting this issue and many thanks to @idietmoran for the quick fix.
