### ISSUE TITLE
Crash if UserSettings.xml is missing

### ISSUE THREAD

**Issue by smaragdus** [dfs-minded/indexer-plus-plus#37]
If configuration file **UserSettings.xml** is missing **Indexer++** crashes. I suggest that if **UserSettings.xml** is not to be found in program folder for some reason (deleted accidentally for example), **Indexer++** should be able to re-create it automatically in stead of crashing.

**Comment by idietmoran** [comment]
This should be fairly easy to implement. What are the default settings, the ones in the repo?

**Comment by dfs-minded** [comment]
Hi! Sounds good. 
All the work with settings located in IndexerGUI project, UserSettings.cs. There is also a UserSettings.xml included in the project, which should be used as the template for recreation.

**Comment by idietmoran** [comment]
I can do this. How do you want to handle an error in the event the program lacks permission to write the file? Should we display the error to the user?

I'm a fan of having an error class with an `enum` that you can keep adding to to check for errors, but I will defer to your judgement.

**Comment by dfs-minded** [comment]
Fixed and merged to master. The update will be available in v0.6. 
Thanks!
